// *****************************************************************************
// Copyright (C) 2017 TypeFox and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0
// *****************************************************************************

import * as fs from 'fs-extra';
import { AbstractGenerator } from './abstract-generator';

export class BundlerGenerator extends AbstractGenerator {

    async generate(): Promise<void> {
        await this.warnAboutWebpackConfig();
        await this.write(this.genESBuildBrowserPath, this.compileESBuildBrowserConfig());
        if (!this.pck.isBrowserOnly()) {
            await this.write(this.genESBuildNodePath, this.compileESBuildNodeConfig());
            if (this.pck.isElectron()) {
                await this.write(this.genESBuildElectronPath, this.compileESBuildElectronConfig());
            }
        }
        if (await this.shouldGenerateUserESBuildConfig()) {
            await this.write(this.esbuildPath, this.compileESBuildUserConfig());
        }
    }

    /**
     * Warns about a `webpack.config.js` left over from Theia < 1.75.0. Such a file is no longer
     * read, so any customization it contains no longer has an effect. Without this warning,
     * adopters would only notice through a differently behaving bundle.
     */
    protected async warnAboutWebpackConfig(): Promise<void> {
        if (await fs.pathExists(this.webpackConfigPath)) {
            console.warn(`Ignoring '${this.webpackConfigPath}': webpack bundling was removed in Theia 1.75.0, '${this.esbuildPath}' is used instead.`);
            console.warn('Port any customization to the esbuild configuration and delete the webpack files. See the migration guide for details: '
                + 'https://github.com/eclipse-theia/theia/blob/master/doc/Migration.md');
        }
    }

    protected async shouldGenerateUserESBuildConfig(): Promise<boolean> {
        if (!(await fs.pathExists(this.esbuildPath))) {
            return true;
        }
        const content = await fs.readFile(this.esbuildPath, 'utf8');
        return !content.includes('gen-esbuild');
    }

    get webpackConfigPath(): string {
        return this.pck.path('webpack.config.js');
    }

    get esbuildPath(): string {
        return this.pck.path('esbuild.mjs');
    }

    get genESBuildBrowserPath(): string {
        return this.pck.path('gen-esbuild.browser.mjs');
    }

    get genESBuildNodePath(): string {
        return this.pck.path('gen-esbuild.node.mjs');
    }

    get genESBuildElectronPath(): string {
        return this.pck.path('gen-esbuild.electron.mjs');
    }

    protected compileESBuildBrowserConfig(): string {
        return `/**
 * Don't touch this file. It will be regenerated by theia build.
 * To customize the build process, change ./esbuild.mjs
 */
import { nodeModulesPolyfillPlugin } from 'esbuild-plugins-node-modules-polyfill';
import { copy } from 'esbuild-plugin-copy';
import { compressAssetsPlugin, monacoNlsPlugin, problemMatcherPlugin, sourceMapPathsPlugin } from '@theia/bundle-plugin';
import yargs from 'yargs';
import { hideBin } from 'yargs/helpers';
import resolvePackagePath from 'resolve-package-path';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const __dirname = path.dirname(fileURLToPath(import.meta.url));

export function join(...parts) {
    return path.join(...parts).replace(/\\\\/g, '/');
}

const { mode, watch, staticCompression } = yargs(hideBin(process.argv)).option('mode', {
    description: "Mode to use",
    choices: ["development", "production"],
    default: "production"
}).option('watch', {
    description: 'Controls whether to enable watch mode',
    type: 'boolean',
    default: false
}).option('static-compression', {
    description: ${this.ifElectron(
        "'Controls whether to emit gzipped copies of the frontend assets. Disabled by default for Electron applications.'",
        "'Controls whether to emit gzipped copies of the frontend assets. Enabled by default in production mode.'")},
    type: 'boolean'
}).argv;

const production = mode === 'production';
const sourcemap = production ? false : 'linked';
const minify = production;
${this.ifElectron(
        `// Electron loads the frontend from the local backend over loopback, where gzip saves nothing
// while the compressed copies still add to the size of the packaged application.
const compression = staticCompression ?? false;`,
        `// Compressing on every rebuild would slow down watch mode, so this only pays off for production builds.
const compression = staticCompression ?? production;`)}

export { mode, watch, sourcemap, minify, compression };

/**
 * @type {Record<string, import('esbuild').Loader>}
 */
export const loader = {
    '.css': 'css',
    '.ttf': 'dataurl',
    '.eot': 'dataurl',
    '.svg': 'dataurl',
    '.woff': 'dataurl',
    '.woff2': 'dataurl',
    '.jpg': 'dataurl',
    '.png': 'dataurl',
    '.gif': 'dataurl',
    '.wasm': 'dataurl',
    '.plist': 'dataurl',
    '.node': 'file'
};

/**
 * @type {import('esbuild').BuildOptions}
 */
export const browserOptions = {
    entryPoints: {
        'bundle': './src-gen/frontend/index.js',
        'secondary-window': './src-gen/frontend/secondary-index.js',
        ${this.ifMonaco(() => "'editor.worker': '@theia/monaco-editor-core/esm/vs/editor/common/services/editorWebWorkerMain.js',")}
        ${this.ifPackage('@theia/plugin-ext', "'plugin-worker': '@theia/plugin-ext/lib/hosted/browser/worker/worker-main.js',")}
    },
    assetNames: '[name]',
    bundle: true,
    outdir: 'lib/frontend',
    platform: 'browser',
    // Support UMD libraries
    // but ensure that we also prioritize browser exports where possible
    mainFields: ['browser', 'module', 'main'],
    loader,
    minify,
    sourcemap,
    plugins: [
        problemMatcherPlugin(watch, 'browser'),
        ${this.ifMonaco(() => 'monacoNlsPlugin(),')}
        nodeModulesPolyfillPlugin({
            globals: {
                Buffer: true,
                process: false
            }
        }),
        copy({
            assets: [
                {
                    // copy secondary window html file to lib folder
                    from: join(__dirname, 'src-gen/frontend/secondary-window.html'),
                    to: join(__dirname, 'lib', 'frontend')
                }${this.ifPackage('@theia/plugin-ext', `,
                {
                    // copy webview files to lib folder
                    from: join(resolvePackagePath('@theia/plugin-ext', __dirname), '..', 'src', 'main', 'browser', 'webview', 'pre', '*'),
                    to: join(__dirname, 'lib', 'webview', 'pre')
                }`)}${this.ifPackage('@theia/plugin-ext-vscode', `,
                {
                    // copy frontend plugin host files
                    from: join(resolvePackagePath('@theia/plugin-ext-vscode', __dirname), '..', 'lib', 'node', 'context', 'plugin-vscode-init-fe.js'),
                    to: join(__dirname, 'lib', 'frontend', 'context')
                }`)}
            ]
        }),
        sourceMapPathsPlugin(),
        // Keep last: it compresses whatever the preceding plugins emitted.
        compressAssetsPlugin({ compress: compression })
    ]
};
`;
    }

    protected compileESBuildNodeConfig(): string {
        return `/**
 * Don't touch this file. It will be regenerated by theia build.
 * To customize the build process, change ./esbuild.mjs
 */
import { nativeDependenciesPlugin, problemMatcherPlugin, sourceMapPathsPlugin } from '@theia/bundle-plugin';
import { watch, loader, minify, sourcemap, join, __dirname } from './gen-esbuild.browser.mjs';
import { copy } from 'esbuild-plugin-copy';
import resolvePackagePath from 'resolve-package-path';

/**
 * @type {Record<string, string>}
 */
export const nativeBindings = {
    drivelist: 'drivelist/build/Release/drivelist.node'
};

/**
 * @type {import('esbuild').BuildOptions}
 */
export const nodeOptions = {
    entryPoints: {
        'main': './src-gen/backend/main',
        'ipc-bootstrap': '@theia/core/lib/node/messaging/ipc-bootstrap',
        ${this.ifElectron("'electron-main': './src-gen/backend/electron-main',")}
        ${this.ifPackage('@theia/plugin-ext', () => `// VS Code extension support:
        'plugin-host': '@theia/plugin-ext/lib/hosted/node/plugin-host',`)}
        ${this.ifPackage('@theia/plugin-ext-headless', () => `// Theia Headless Plugin support:
        'plugin-host-headless': '@theia/plugin-ext-headless/lib/hosted/node/plugin-host-headless',`)}
        ${this.ifPackage('@theia/process', () => `// Make sure the node-pty thread workers can be executed:
        'worker/conoutSocketWorker': 'node-pty/lib/worker/conoutSocketWorker',
        'conpty_console_list_agent': 'node-pty/lib/conpty_console_list_agent',`)}
        ${this.ifPackage('@theia/dev-container', () => `// VS Code Dev-Container communication:
        'dev-container-server': '@theia/dev-container/lib/dev-container-server/dev-container-server',`)}
        ${this.ifPackage('@theia/plugin-ext', "'backend-init-theia': '@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia',")}
        ${this.ifPackage('@theia/filesystem', "'parcel-watcher': '@theia/filesystem/lib/node/parcel-watcher',")}
        ${this.ifPackage('@theia/plugin-ext-vscode', "'plugin-vscode-init': '@theia/plugin-ext-vscode/lib/node/plugin-vscode-init',")}
        ${this.ifPackage('@theia/api-provider-sample', "'gotd-api-init': '@theia/api-provider-sample/lib/plugin/gotd-api-init',")}
        ${this.ifPackage('@theia/git', "'git-locator-host': '@theia/git/lib/node/git-locator/git-locator-host',")}
    },
    assetNames: 'native/[name]',
    bundle: true,
    outdir: 'lib/backend',
    platform: 'node',
    mainFields: ['node', 'module', 'main'],
    external: ['electron'],
    loader,
    minify,
    sourcemap,
    plugins: [
        problemMatcherPlugin(watch, 'node'),
        nativeDependenciesPlugin({
            pty: ${this.ifPackage('@theia/process', 'true', 'false')},
            ripgrep: ${this.ifPackage(['@theia/search-in-workspace', '@theia/file-search'], 'true', 'false')},
            trash: ${this.ifPackage('@theia/filesystem', 'true', 'false')},
            nativeBindings
        }),
        copy({
            assets: [${this.ifPackage('@theia/terminal', `
                {
                    // copy shell integration scripts
                    from: join(resolvePackagePath('@theia/terminal', __dirname), '..', 'src', 'node', 'shell-integrations', '**', '*'),
                    to: join(__dirname, 'lib', 'backend', 'shell-integrations')
                },`)}
            ]
        }),
        sourceMapPathsPlugin()
    ]
};
`;
    }

    protected compileESBuildUserConfig(): string {
        return `/**
 * This file can be edited to adjust the ESBuild build process.
 * To reset, delete this file and rerun theia build again.
 */
import { browserOptions, watch } from './gen-esbuild.browser.mjs';
${this.ifBrowserOnly(`import esbuild from 'esbuild';

const browserContext = await esbuild.context(browserOptions);

if (watch) {
    await browserContext.watch();
} else {
    try {
        await browserContext.rebuild();
        await browserContext.dispose();
    } catch {
        process.exit(1);
    }
}`, `import { nodeOptions } from './gen-esbuild.node.mjs';
${this.ifElectron("import { electronOptions } from './gen-esbuild.electron.mjs';")}
import esbuild from 'esbuild';

const browserContext = await esbuild.context(browserOptions);
const nodeContext = await esbuild.context(nodeOptions);
${this.ifElectron('const electronContext = await esbuild.context(electronOptions);')}

if (watch) {
    await Promise.all([
        browserContext.watch(),
        nodeContext.watch(),${this.ifElectron(`
        electronContext.watch(),`)}
    ]);
} else {
    try {
        await browserContext.rebuild();
        await browserContext.dispose();
        await nodeContext.rebuild();
        await nodeContext.dispose();${this.ifElectron(`
        await electronContext.rebuild();
        await electronContext.dispose();`)}
    } catch {
        process.exit(1);
    }
}`)}
`;
    }

    protected compileESBuildElectronConfig(): string {
        return `/**
 * Don't touch this file. It will be regenerated by theia build.
 * To customize the build process, change ./esbuild.mjs
 */
import { problemMatcherPlugin, sourceMapPathsPlugin } from '@theia/bundle-plugin';
import { watch, loader, minify, sourcemap } from './gen-esbuild.browser.mjs';

/**
 * @type {import('esbuild').BuildOptions}
 */
export const electronOptions = {
    entryPoints: {
        'preload': './src-gen/frontend/preload'
    },
    bundle: true,
    outdir: 'lib/frontend',
    platform: 'node',
    mainFields: ['node', 'module', 'main'],
    external: ['electron'],
    loader,
    minify,
    sourcemap,
    plugins: [
        problemMatcherPlugin(watch, 'electron'),
        sourceMapPathsPlugin()
    ]
};
`;
    }

}
