image:
  file: .gitpod.dockerfile
ports:
  - port: 3000 # Theia
  - port: 3030 # VS Code extension tests
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 9229 # Node.js debug port
    onOpen: ignore
  - port: 9339 # Node.js debug port
    onOpen: ignore
tasks:
  - init: yarn --network-timeout 100000 && yarn browser build && yarn download:plugins
    command: >
      jwm &
      yarn browser start ../.. --hostname=0.0.0.0
vscode:
  extensions:
    - dbaeumer.vscode-eslint
