image:
  file: .gitpod.dockerfile
ports:
  - port: 3000 # Theia
  - port: 3030 # VS Code extension tests
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 9229 # Node.js debug port
    onOpen: ignore
  - port: 9339 # Node.js debug port
    onOpen: ignore
tasks:
  - init: yarn --network-timeout 100000 && yarn build:examples && yarn download:plugins
    command: >
      jwm &
      yarn --cwd examples/browser start ../.. --hostname=0.0.0.0
github:
  prebuilds:
    pullRequestsFromForks: true
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.0.0:CwAMx4wYz1Kq39+1Aul4VQ==
