image:
  file: .gitpod.dockerfile
ports:
- port: 3000 # Theia
- port: 3030 # VS Code extension tests
- port: 9339 # Node.js debug port
  onOpen: ignore
- port: 6080
  onOpen: ignore
- port: 5900
  onOpen: ignore
tasks:
- init: yarn
  command: >
    jwm &
    yarn --cwd examples/browser start ../.. --hostname=0.0.0.0
github:
  prebuilds:
    pullRequestsFromForks: true
