labels: []
body:
  - type: textarea
    id: improvement
    attributes:
      label: Improvement Description
      description: Describe the improvement you'd like to see in Eclipse Theia.
      placeholder: Describe the improvement here...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

        💙 Eclipse Theia is community-supported. If you find it valuable, consider supporting the project: https://theia-ide.org/support/
