name: Prompt Template Submission
description: Submit a prompt template, detailing its functionality and tested results.
title: Prompt Template for <Agent Name> <Describe Functionality>
body:
  - type: textarea
    id: what_template_does
    attributes:
      label: What Does This Template Do?
      description: Provide a brief description of the prompt template. What problem does it solve? What specific functionality and agent does it enhance and how? 
      placeholder: Enter a description of the template.
    validations:
      required: true

  - type: textarea
    id: prompt_template
    attributes:
      label: The Prompt Template
      description: Paste your prompt template here as plain text.
      placeholder: Enter the prompt template.
    validations:
      required: true

  - type: textarea
    id: tested_llms
    attributes:
      label: Tested LLMs
      description: List the language models this template has been tested with, including versions, providers, and notable performance observations.
      placeholder: |- 
        - LLM Name & Version (e.g., OpenAI GPT-4)
        - Provider (e.g., OpenAI, llama-file, Ollama)
        - Observations or challenges
    validations:
      required: true

  - type: textarea
    id: example_requests
    attributes:
      label: Example User Requests
      description: Provide some example user requests tested with this template.
      placeholder: |- 
        1. Example Request 1: [User input]
        2. Example Request 2: [User input]
        3. Example Request 3: [User input]
    validations:
      required: true

  - type: textarea
    id: improvement_suggestions
    attributes:
      label: Suggestions for Improvements (Optional)
      description: Share any known limitations or ideas for improving the template.
      placeholder: Describe any challenges or potential enhancements.
    validations:
      required: false

  - type: textarea
    id: related_resources
    attributes:
      label: Related Discussions or Resources (Optional)
      description: Link to any relevant discussions, documentation, or resources that could help others understand or improve your template.
      placeholder: Provide URLs or references.
    validations:
      required: false

  - type: checkboxes
    id: license_agreement
    attributes:
      label: License Agreement
      description: By submitting this template, you agree to the following terms
      options:
        - label: |
            By submitting this template, you agree to the following:

            1. Your submission is contributed under the [MIT License](https://opensource.org/licenses/MIT).
            2. You certify that your contribution complies with the **Developer Certificate of Origin (DCO) Version 1.1**, outlined below:

            ### Developer Certificate of Origin 1.1

            Copyright (C) 2004, 2006 The Linux Foundation and its contributors.  
            660 York Street, Suite 102, San Francisco, CA 94110 USA

            Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

            #### Developer's Certificate of Origin 1.1

            By making a contribution to this project, I certify that:

            (a) The contribution was created in whole or in part by me and I have the right to submit it under the open-source license indicated in the file; or  
            (b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open-source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open-source license (unless I am permitted to submit under a different license), as indicated in the file; or  
            (c) The contribution was provided directly to me by some other person who certified (a), (b), or (c) and I have not modified it.  

            (d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my signoff) is maintained indefinitely and may be redistributed consistent with this project or the open-source license(s) involved.

            I agree to contribute this submission under the MIT License and certify compliance with the Developer Certificate of Origin (DCO) Version 1.1.
          required: true
