/********************************************************************************
 * Copyright (C) 2021 Ericsson and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License, version 2
 * with the GNU Classpath Exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 ********************************************************************************/

import { injectable } from 'inversify';
import { Disposable, DisposableCollection, Emitter } from '../common';

export interface IconDefinition {
    id?: string;
    fontId?: string;
    fontCharacter: string;
}
export interface IconContribution {
    id: string;
    defaults?: IconDefinition;
    description?: string;
}

@injectable()
export class IconRegistry {
    protected readonly onDidChangeEmitter = new Emitter<void>();
    readonly onDidChange = this.onDidChangeEmitter.event;
    protected fireDidChange(): void {
        this.onDidChangeEmitter.fire(undefined);
    }

    protected readonly _icons = new Map<string, IconDefinition | undefined>();

    getIconById(iconId: string): IconDefinition | undefined {
        return this._icons.get(iconId);
    }

    get icons(): IterableIterator<[string, IconDefinition | undefined]> {
        return this._icons.entries();
    }

    register(...iconContributions: IconContribution[]): Disposable {
        const toDispose = new DisposableCollection();
        iconContributions.forEach(contribution => {
            if (this._icons.has(contribution.id)) {
                throw new Error(`Icon with ID ${contribution.id} already exists`);
            }
            this._icons.set(contribution.id, contribution.defaults);
            toDispose.push(this.createDisposableForRegistration(contribution));
        });
        this.fireDidChange();
        return toDispose;
    }

    protected createDisposableForRegistration(iconContribution: IconContribution): Disposable {
        return Disposable.create(() => {
            this._icons.delete(iconContribution.id);
        });
    }
}

export class Codicon implements IconDefinition {
    public readonly id: string;
    public readonly fontId: string | undefined;
    public readonly fontCharacter: string;

    constructor(id: string, definition: IconDefinition) {
        const { fontId, fontCharacter } = definition;
        this.id = id;
        this.fontId = fontId;
        this.fontCharacter = fontCharacter;
    }

    get classNames(): string {
        return `codicon codicon-${this.fontId}`;
    }
    get selector(): string {
        return `.codicon.codicon-${this.id}`;
    }
}

/*
* Should align with https://code.visualstudio.com/api/references/icons-in-labels
*/
export const ProductCodicons = [
    { id: 'accounts-view-bar-icon', defaults: new Codicon('account', { fontCharacter: '\\eb99' }) },
    { id: 'breakpoints-activate', defaults: new Codicon('activate-breakpoints', { fontCharacter: '\\ea97' }) },
    { id: 'diff-insert', defaults: new Codicon('add', { fontCharacter: '\\ea60' }) },
    { id: 'diff-review-insert', defaults: new Codicon('add', { fontCharacter: '\\ea60' }) },
    { id: 'keybindings-add', defaults: new Codicon('add', { fontCharacter: '\\ea60' }) },
    { id: 'settings-add', defaults: new Codicon('add', { fontCharacter: '\\ea60' }) },
    { id: 'terminal-new', defaults: new Codicon('add', { fontCharacter: '\\ea60' }) },
    { id: 'watch-expressions-add', defaults: new Codicon('add', { fontCharacter: '\\ea60' }) },
    { id: 'watch-expressions-add-function-breakpoint', defaults: new Codicon('add', { fontCharacter: '\\ea60' }) },
    { id: 'diff-editor-next-change', defaults: new Codicon('arrow-down', { fontCharacter: '\\ea9a' }) },
    { id: 'find-next-match', defaults: new Codicon('arrow-down', { fontCharacter: '\\ea9a' }) },
    { id: 'goto-next-location', defaults: new Codicon('arrow-down', { fontCharacter: '\\ea9a' }) },
    { id: 'notebook-move-down', defaults: new Codicon('arrow-down', { fontCharacter: '\\ea9a' }) },
    { id: 'debug-console-evaluation-input', defaults: new Codicon('arrow-small-right', { fontCharacter: '\\ea9f' }) },
    { id: 'diff-editor-previous-change', defaults: new Codicon('arrow-up', { fontCharacter: '\\eaa1' }) },
    { id: 'find-previous-match', defaults: new Codicon('arrow-up', { fontCharacter: '\\eaa1' }) },
    { id: 'goto-previous-location', defaults: new Codicon('arrow-up', { fontCharacter: '\\eaa1' }) },
    { id: 'notebook-move-up', defaults: new Codicon('arrow-up', { fontCharacter: '\\eaa1' }) },
    { id: 'test-view-icon', defaults: new Codicon('beaker', { fontCharacter: '\\ea79' }) },
    { id: 'open-editors-view-icon', defaults: new Codicon('book', { fontCharacter: '\\eaa4' }) },
    { id: 'remote-explorer-documentation', defaults: new Codicon('book', { fontCharacter: '\\eaa4' }) },
    { id: 'callstack-view-session', defaults: new Codicon('bug', { fontCharacter: '\\eaaf' }) },
    { id: 'callhierarchy-incoming', defaults: new Codicon('call-incoming', { fontCharacter: '\\eb92' }) },
    { id: 'callhierarchy-outgoing', defaults: new Codicon('call-outgoing', { fontCharacter: '\\eb93' }) },
    { id: 'notebook-state-success', defaults: new Codicon('check', { fontCharacter: '\\eab2' }) },
    { id: 'notebook-stop-edit', defaults: new Codicon('check', { fontCharacter: '\\eab2' }) },
    { id: 'find-expanded', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'folding-expanded', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'marker-navigation-next', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'markers-view-multi-line-collapsed', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'notebook-expanded', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'notifications-collapse', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'notifications-hide', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'panel-restore', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'parameter-hints-next', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'search-show-replace', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'settings-group-expanded', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'view-pane-container-expanded', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    { id: 'debug-console-evaluation-prompt', defaults: new Codicon('chevron-right', { fontCharacter: '\\eab6' }) },
    { id: 'find-collapsed', defaults: new Codicon('chevron-right', { fontCharacter: '\\eab6' }) },
    { id: 'folding-collapsed', defaults: new Codicon('chevron-right', { fontCharacter: '\\eab6' }) },
    { id: 'notebook-collapsed', defaults: new Codicon('chevron-right', { fontCharacter: '\\eab6' }) },
    { id: 'search-hide-replace', defaults: new Codicon('chevron-right', { fontCharacter: '\\eab6' }) },
    { id: 'settings-group-collapsed', defaults: new Codicon('chevron-right', { fontCharacter: '\\eab6' }) },
    { id: 'suggest-more-info', defaults: new Codicon('chevron-right', { fontCharacter: '\\eab6' }) },
    { id: 'view-pane-container-collapsed', defaults: new Codicon('chevron-right', { fontCharacter: '\\eab6' }) },
    { id: 'marker-navigation-previous', defaults: new Codicon('chevron-up', { fontCharacter: '\\eab7' }) },
    { id: 'markers-view-multi-line-expanded', defaults: new Codicon('chevron-up', { fontCharacter: '\\eab7' }) },
    { id: 'notifications-expand', defaults: new Codicon('chevron-up', { fontCharacter: '\\eab7' }) },
    { id: 'panel-maximize', defaults: new Codicon('chevron-up', { fontCharacter: '\\eab7' }) },
    { id: 'parameter-hints-previous', defaults: new Codicon('chevron-up', { fontCharacter: '\\eab7' }) },
    { id: 'review-comment-collapse', defaults: new Codicon('chevron-up', { fontCharacter: '\\eab7' }) },
    { id: 'getting-started-item-unchecked', defaults: new Codicon('circle-large-outline', { fontCharacter: '\\ebb5' }) },
    { id: 'testing-unset-icon', defaults: new Codicon('circle-outline', { fontCharacter: '\\eabc' }) },
    { id: 'debug-console-clear-all', defaults: new Codicon('clear-all', { fontCharacter: '\\eabf' }) },
    { id: 'extensions-clear-search-results', defaults: new Codicon('clear-all', { fontCharacter: '\\eabf' }) },
    { id: 'notebook-clear', defaults: new Codicon('clear-all', { fontCharacter: '\\eabf' }) },
    { id: 'notifications-clear-all', defaults: new Codicon('clear-all', { fontCharacter: '\\eabf' }) },
    { id: 'preferences-clear-input', defaults: new Codicon('clear-all', { fontCharacter: '\\eabf' }) },
    { id: 'search-clear-results', defaults: new Codicon('clear-all', { fontCharacter: '\\eabf' }) },
    { id: 'diff-review-close', defaults: new Codicon('close', { fontCharacter: '\\ea76' }) },
    { id: 'notifications-clear', defaults: new Codicon('close', { fontCharacter: '\\ea76' }) },
    { id: 'panel-close', defaults: new Codicon('close', { fontCharacter: '\\ea76' }) },
    { id: 'search-remove', defaults: new Codicon('close', { fontCharacter: '\\ea76' }) },
    { id: 'settings-remove', defaults: new Codicon('close', { fontCharacter: '\\ea76' }) },
    { id: 'tasks-remove', defaults: new Codicon('close', { fontCharacter: '\\ea76' }) },
    { id: 'testing-cancel-icon', defaults: new Codicon('close', { fontCharacter: '\\ea76' }) },
    { id: 'testing-failed-icon', defaults: new Codicon('close', { fontCharacter: '\\ea76' }) },
    { id: 'widget-close', defaults: new Codicon('close', { fontCharacter: '\\ea76' }) },
    { id: 'breakpoints-remove-all', defaults: new Codicon('close-all', { fontCharacter: '\\eac1' }) },
    { id: 'watch-expressions-remove-all', defaults: new Codicon('close-all', { fontCharacter: '\\eac1' }) },
    { id: 'extensions-install-count', defaults: new Codicon('cloud-download', { fontCharacter: '\\eac2' }) },
    { id: 'extensions-install-local-in-remote', defaults: new Codicon('cloud-download', { fontCharacter: '\\eac2' }) },
    { id: 'extensions-install-workspace-recommended', defaults: new Codicon('cloud-download', { fontCharacter: '\\eac2' }) },
    { id: 'notebook-mimetype', defaults: new Codicon('code', { fontCharacter: '\\eac4' }) },
    { id: 'debug-collapse-all', defaults: new Codicon('collapse-all', { fontCharacter: '\\eac5' }) },
    { id: 'search-collapse-results', defaults: new Codicon('collapse-all', { fontCharacter: '\\eac5' }) },
    { id: 'remote-explorer-report-issues', defaults: new Codicon('comment', { fontCharacter: '\\ea6b' }) },
    { id: 'comments-view-icon', defaults: new Codicon('comment-discussion', { fontCharacter: '\\eac7' }) },
    { id: 'breakpoints-view-icon', defaults: new Codicon('debug-alt', { fontCharacter: '\\eb91' }) },
    { id: 'callstack-view-icon', defaults: new Codicon('debug-alt', { fontCharacter: '\\eb91' }) },
    { id: 'loaded-scripts-view-icon', defaults: new Codicon('debug-alt', { fontCharacter: '\\eb91' }) },
    { id: 'run-view-icon', defaults: new Codicon('debug-alt', { fontCharacter: '\\eb91' }) },
    { id: 'testing-debug-icon', defaults: new Codicon('debug-alt', { fontCharacter: '\\eb91' }) },
    { id: 'variables-view-icon', defaults: new Codicon('debug-alt', { fontCharacter: '\\eb91' }) },
    { id: 'watch-view-icon', defaults: new Codicon('debug-alt', { fontCharacter: '\\eb91' }) },
    { id: 'debug-breakpoint', defaults: new Codicon('debug-breakpoint', { fontCharacter: '\\ea71' }) },
    { id: 'debug-breakpoint-conditional', defaults: new Codicon('debug-breakpoint-conditional', { fontCharacter: '\\eaa7' }) },
    { id: 'debug-breakpoint-conditional-disabled', defaults: new Codicon('debug-breakpoint-conditional-disabled', { fontCharacter: '\\eaa7' }) },
    { id: 'debug-breakpoint-conditional-unverified', defaults: new Codicon('debug-breakpoint-conditional-unverified', { fontCharacter: '\\eaa6' }) },
    { id: 'debug-breakpoint-data', defaults: new Codicon('debug-breakpoint-data', { fontCharacter: '\\eaa9' }) },
    { id: 'debug-breakpoint-data-disabled', defaults: new Codicon('debug-breakpoint-data-disabled', { fontCharacter: '\\eaa9' }) },
    { id: 'debug-breakpoint-data-unverified', defaults: new Codicon('debug-breakpoint-data-unverified', { fontCharacter: '\\eaa8' }) },
    { id: 'debug-breakpoint-disabled', defaults: new Codicon('debug-breakpoint-disabled', { fontCharacter: '\\ea71' }) },
    { id: 'debug-breakpoint-function', defaults: new Codicon('debug-breakpoint-function', { fontCharacter: '\\eb88' }) },
    { id: 'debug-breakpoint-function-disabled', defaults: new Codicon('debug-breakpoint-function-disabled', { fontCharacter: '\\eb88' }) },
    { id: 'debug-breakpoint-function-unverified', defaults: new Codicon('debug-breakpoint-function-unverified', { fontCharacter: '\\eb87' }) },
    { id: 'debug-breakpoint-log', defaults: new Codicon('debug-breakpoint-log', { fontCharacter: '\\eaab' }) },
    { id: 'debug-breakpoint-log-disabled', defaults: new Codicon('debug-breakpoint-log-disabled', { fontCharacter: '\\eaab' }) },
    { id: 'debug-breakpoint-log-unverified', defaults: new Codicon('debug-breakpoint-log-unverified', { fontCharacter: '\\eaaa' }) },
    { id: 'debug-breakpoint-unsupported', defaults: new Codicon('debug-breakpoint-unsupported', { fontCharacter: '\\eb8c' }) },
    { id: 'debug-breakpoint-unverified', defaults: new Codicon('debug-breakpoint-unverified', { fontCharacter: '\\eabc' }) },
    { id: 'debug-console', defaults: new Codicon('debug-console', { fontCharacter: '\\eb9b' }) },
    { id: 'debug-console-view-icon', defaults: new Codicon('debug-console', { fontCharacter: '\\eb9b' }) },
    { id: 'debug-continue', defaults: new Codicon('debug-continue', { fontCharacter: '\\eacf' }) },
    { id: 'debug-disconnect', defaults: new Codicon('debug-disconnect', { fontCharacter: '\\ead0' }) },
    { id: 'debug-hint', defaults: new Codicon('debug-hint', { fontCharacter: '\\ea71' }) },
    { id: 'debug-pause', defaults: new Codicon('debug-pause', { fontCharacter: '\\ead1' }) },
    { id: 'debug-restart', defaults: new Codicon('debug-restart', { fontCharacter: '\\ead2' }) },
    { id: 'debug-restart-frame', defaults: new Codicon('debug-restart-frame', { fontCharacter: '\\eb90' }) },
    { id: 'debug-reverse-continue', defaults: new Codicon('debug-reverse-continue', { fontCharacter: '\\eb8e' }) },
    { id: 'debug-stackframe', defaults: new Codicon('debug-stackframe', { fontCharacter: '\\eb8b' }) },
    { id: 'debug-stackframe-focused', defaults: new Codicon('debug-stackframe-focused', { fontCharacter: '\\eb8b' }) },
    { id: 'debug-start', defaults: new Codicon('debug-start', { fontCharacter: '\\ead3' }) },
    { id: 'debug-step-back', defaults: new Codicon('debug-step-back', { fontCharacter: '\\eb8f' }) },
    { id: 'debug-step-into', defaults: new Codicon('debug-step-into', { fontCharacter: '\\ead4' }) },
    { id: 'debug-step-out', defaults: new Codicon('debug-step-out', { fontCharacter: '\\ead5' }) },
    { id: 'debug-step-over', defaults: new Codicon('debug-step-over', { fontCharacter: '\\ead6' }) },
    { id: 'testing-skipped-icon', defaults: new Codicon('debug-step-over', { fontCharacter: '\\ead6' }) },
    { id: 'debug-stop', defaults: new Codicon('debug-stop', { fontCharacter: '\\ead7' }) },
    { id: 'notebook-revert', defaults: new Codicon('discard', { fontCharacter: '\\eae2' }) },
    { id: 'settings-discard', defaults: new Codicon('discard', { fontCharacter: '\\eae2' }) },
    { id: 'keybindings-edit', defaults: new Codicon('edit', { fontCharacter: '\\ea73' }) },
    { id: 'settings-edit', defaults: new Codicon('edit', { fontCharacter: '\\ea73' }) },
    { id: 'search-details', defaults: new Codicon('ellipsis', { fontCharacter: '\\ea7c' }) },
    { id: 'notebook-state-error', defaults: new Codicon('error', { fontCharacter: '\\ea87' }) },
    { id: 'search-expand-results', defaults: new Codicon('expand-all', { fontCharacter: '\\eb95' }) },
    { id: 'extensions-view-icon', defaults: new Codicon('extensions', { fontCharacter: '\\eae6' }) },
    { id: 'public-ports-view-icon', defaults: new Codicon('eye', { fontCharacter: '\\ea70' }) },
    { id: 'notebook-open-as-text', defaults: new Codicon('file-code', { fontCharacter: '\\eae9' }) },
    { id: 'explorer-view-icon', defaults: new Codicon('files', { fontCharacter: '\\eaf0' }) },
    { id: 'extensions-filter', defaults: new Codicon('filter', { fontCharacter: '\\eaf1' }) },
    { id: 'markers-view-filter', defaults: new Codicon('filter', { fontCharacter: '\\eaf1' }) },
    { id: 'debug-configure', defaults: new Codicon('gear', { fontCharacter: '\\eaf8' }) },
    { id: 'extensions-manage', defaults: new Codicon('gear', { fontCharacter: '\\eaf8' }) },
    { id: 'notifications-configure', defaults: new Codicon('gear', { fontCharacter: '\\eaf8' }) },
    { id: 'settings-more-action', defaults: new Codicon('gear', { fontCharacter: '\\eaf8' }) },
    { id: 'tasks-list-configure', defaults: new Codicon('gear', { fontCharacter: '\\eaf8' }) },
    { id: 'terminal-rename', defaults: new Codicon('gear', { fontCharacter: '\\eaf8' }) },
    { id: 'getting-started-codespaces', defaults: new Codicon('github', { fontCharacter: '\\ea84' }) },
    { id: 'ports-open-browser-icon', defaults: new Codicon('globe', { fontCharacter: '\\eb01' }) },
    { id: 'preferences-open-settings', defaults: new Codicon('go-to-file', { fontCharacter: '\\ea94' }) },
    { id: 'debug-gripper', defaults: new Codicon('gripper', { fontCharacter: '\\eb04' }) },
    { id: 'getting-started-setup', defaults: new Codicon('heart', { fontCharacter: '\\eb05' }) },
    { id: 'timeline-open', defaults: new Codicon('history', { fontCharacter: '\\ea82' }) },
    { id: 'timeline-view-icon', defaults: new Codicon('history', { fontCharacter: '\\ea82' }) },
    { id: 'extensions-info-message', defaults: new Codicon('info', { fontCharacter: '\\ea74' }) },
    { id: 'remote-explorer-review-issues', defaults: new Codicon('issues', { fontCharacter: '\\eb0c' }) },
    { id: 'getting-started-beginner', defaults: new Codicon('lightbulb', { fontCharacter: '\\ea61' }) },
    { id: 'refactor-preview-view-icon', defaults: new Codicon('lightbulb', { fontCharacter: '\\ea61' }) },
    { id: 'search-show-context', defaults: new Codicon('list-selection', { fontCharacter: '\\eb85' }) },
    { id: 'testing-show-as-list-icon', defaults: new Codicon('list-tree', { fontCharacter: '\\eb86' }) },
    { id: 'private-ports-view-icon', defaults: new Codicon('lock', { fontCharacter: '\\ea75' }) },
    { id: 'search-new-editor', defaults: new Codicon('new-file', { fontCharacter: '\\ea7f' }) },
    { id: 'output-view-icon', defaults: new Codicon('output', { fontCharacter: '\\eb9d' }) },
    { id: 'testing-passed-icon', defaults: new Codicon('pass', { fontCharacter: '\\eba4' }) },
    { id: 'getting-started-item-checked', defaults: new Codicon('pass-filled', { fontCharacter: '\\ebb3' }) },
    { id: 'extensions-configure-recommended', defaults: new Codicon('pencil', { fontCharacter: '\\ea73' }) },
    { id: 'notebook-edit', defaults: new Codicon('pencil', { fontCharacter: '\\ea73' }) },
    { id: 'timeline-pin', defaults: new Codicon('pin', { fontCharacter: '\\eb2b' }) },
    { id: 'timeline-unpin', defaults: new Codicon('pinned', { fontCharacter: '\\eba0' }) },
    { id: 'notebook-execute', defaults: new Codicon('play', { fontCharacter: '\\eb2c' }) },
    { id: 'ports-view-icon', defaults: new Codicon('plug', { fontCharacter: '\\eb2d' }) },
    { id: 'ports-forward-icon', defaults: new Codicon('plus', { fontCharacter: '\\ea60' }) },
    { id: 'notebook-render-output', defaults: new Codicon('preview', { fontCharacter: '\\eb2f' }) },
    { id: 'notebook-stop', defaults: new Codicon('primitive-square', { fontCharacter: '\\ea72' }) },
    { id: 'keybindings-record-keys', defaults: new Codicon('record-keys', { fontCharacter: '\\ea65' }) },
    { id: 'extensions-refresh', defaults: new Codicon('refresh', { fontCharacter: '\\eb37' }) },
    { id: 'search-refresh', defaults: new Codicon('refresh', { fontCharacter: '\\eb37' }) },
    { id: 'timeline-refresh', defaults: new Codicon('refresh', { fontCharacter: '\\eb37' }) },
    { id: 'extensions-remote', defaults: new Codicon('remote', { fontCharacter: '\\eb3a' }) },
    { id: 'remote-explorer-view-icon', defaults: new Codicon('remote-explorer', { fontCharacter: '\\eb39' }) },
    { id: 'diff-remove', defaults: new Codicon('remove', { fontCharacter: '\\eb3b' }) },
    { id: 'diff-review-remove', defaults: new Codicon('remove', { fontCharacter: '\\eb3b' }) },
    { id: 'find-replace', defaults: new Codicon('replace', { fontCharacter: '\\eb3d' }) },
    { id: 'search-replace', defaults: new Codicon('replace', { fontCharacter: '\\eb3d' }) },
    { id: 'find-replace-all', defaults: new Codicon('replace-all', { fontCharacter: '\\eb3c' }) },
    { id: 'search-replace-all', defaults: new Codicon('replace-all', { fontCharacter: '\\eb3c' }) },
    { id: 'testing-run-icon', defaults: new Codicon('run', { fontCharacter: '\\eb2c' }) },
    { id: 'notebook-execute-all', defaults: new Codicon('run-all', { fontCharacter: '\\eb9e' }) },
    { id: 'testing-run-all-icon', defaults: new Codicon('run-all', { fontCharacter: '\\eb9e' }) },
    { id: 'search-view-icon', defaults: new Codicon('search', { fontCharacter: '\\ea6d' }) },
    { id: 'search-stop', defaults: new Codicon('search-stop', { fontCharacter: '\\eb4e' }) },
    { id: 'find-selection', defaults: new Codicon('selection', { fontCharacter: '\\eb85' }) },
    { id: 'notebook-kernel-select', defaults: new Codicon('server-environment', { fontCharacter: '\\eba3' }) },
    { id: 'notebook-kernel-configure', defaults: new Codicon('settings-gear', { fontCharacter: '\\eb51' }) },
    { id: 'settings-view-bar-icon', defaults: new Codicon('settings-gear', { fontCharacter: '\\eb51' }) },
    { id: 'keybindings-sort', defaults: new Codicon('sort-precedence', { fontCharacter: '\\eb55' }) },
    { id: 'source-control-view-icon', defaults: new Codicon('source-control', { fontCharacter: '\\ea68' }) },
    { id: 'notebook-split-cell', defaults: new Codicon('split-vertical', { fontCharacter: '\\eb57' }) },
    { id: 'extensions-rating', defaults: new Codicon('star', { fontCharacter: '\\ea6a' }) },
    { id: 'remote-explorer-get-started', defaults: new Codicon('star', { fontCharacter: '\\ea6a' }) },
    { id: 'extensions-star-empty', defaults: new Codicon('star-empty', { fontCharacter: '\\ea6a' }) },
    { id: 'extensions-star-full', defaults: new Codicon('star-full', { fontCharacter: '\\eb59' }) },
    { id: 'extensions-star-half', defaults: new Codicon('star-half', { fontCharacter: '\\eb5a' }) },
    { id: 'outline-view-icon', defaults: new Codicon('symbol-class', { fontCharacter: '\\eb5b' }) },
    { id: 'extensions-sync-enabled', defaults: new Codicon('sync', { fontCharacter: '\\ea77' }) },
    { id: 'settings-sync-view-icon', defaults: new Codicon('sync', { fontCharacter: '\\ea77' }) },
    { id: 'extensions-sync-ignored', defaults: new Codicon('sync-ignored', { fontCharacter: '\\eb9f' }) },
    { id: 'terminal-view-icon', defaults: new Codicon('terminal', { fontCharacter: '\\ea85' }) },
    { id: 'notebook-delete-cell', defaults: new Codicon('trash', { fontCharacter: '\\ea81' }) },
    { id: 'terminal-kill', defaults: new Codicon('trash', { fontCharacter: '\\ea81' }) },
    { id: 'settings-folder-dropdown', defaults: new Codicon('triangle-down', { fontCharacter: '\\eb6e' }) },
    { id: 'remote-explorer-feedback', defaults: new Codicon('twitter', { fontCharacter: '\\eb72' }) },
    { id: 'notebook-unfold', defaults: new Codicon('unfold', { fontCharacter: '\\eb73' }) },
    { id: 'extensions-warning-message', defaults: new Codicon('warning', { fontCharacter: '\\ea6c' }) },
    { id: 'markers-view-icon', defaults: new Codicon('warning', { fontCharacter: '\\ea6c' }) },
    { id: 'testing-error-icon', defaults: new Codicon('warning', { fontCharacter: '\\ea6c' }) },
    { id: 'testing-queued-icon', defaults: new Codicon('watch', { fontCharacter: '\\eb7c' }) },
    { id: 'diff-editor-toggle-whitespace', defaults: new Codicon('whitespace', { fontCharacter: '\\eb7d' }) },
    { id: 'default-view-icon', defaults: new Codicon('window', { fontCharacter: '\\eb7f' }) },
    { id: 'ports-stop-forward-icon', defaults: new Codicon('x', { fontCharacter: '\\ea76' }) }
];

// TO DO: CQ needed from VSCode
// export const Codicons = [
    // { id: 'add', defaults: new Codicon('add', { fontCharacter: '\\ea60' }) },
    // { id: 'plus', defaults: new Codicon('plus', { fontCharacter: '\\ea60' }) },
    // { id: 'gist-new', defaults: new Codicon('gist-new', { fontCharacter: '\\ea60' }) },
    // { id: 'repo-create', defaults: new Codicon('repo-create', { fontCharacter: '\\ea60' }) },
    // { id: 'lightbulb', defaults: new Codicon('lightbulb', { fontCharacter: '\\ea61' }) },
    // { id: 'light-bulb', defaults: new Codicon('light-bulb', { fontCharacter: '\\ea61' }) },
    // { id: 'repo', defaults: new Codicon('repo', { fontCharacter: '\\ea62' }) },
    // { id: 'repo-delete', defaults: new Codicon('repo-delete', { fontCharacter: '\\ea62' }) },
    // { id: 'gist-fork', defaults: new Codicon('gist-fork', { fontCharacter: '\\ea63' }) },
    // { id: 'repo-forked', defaults: new Codicon('repo-forked', { fontCharacter: '\\ea63' }) },
    // { id: 'git-pull-request', defaults: new Codicon('git-pull-request', { fontCharacter: '\\ea64' }) },
    // { id: 'git-pull-request-abandoned', defaults: new Codicon('git-pull-request-abandoned', { fontCharacter: '\\ea64' }) },
    // { id: 'record-keys', defaults: new Codicon('record-keys', { fontCharacter: '\\ea65' }) },
    // { id: 'keyboard', defaults: new Codicon('keyboard', { fontCharacter: '\\ea65' }) },
    // { id: 'tag', defaults: new Codicon('tag', { fontCharacter: '\\ea66' }) },
    // { id: 'tag-add', defaults: new Codicon('tag-add', { fontCharacter: '\\ea66' }) },
    // { id: 'tag-remove', defaults: new Codicon('tag-remove', { fontCharacter: '\\ea66' }) },
    // { id: 'person', defaults: new Codicon('person', { fontCharacter: '\\ea67' }) },
    // { id: 'person-follow', defaults: new Codicon('person-follow', { fontCharacter: '\\ea67' }) },
    // { id: 'person-outline', defaults: new Codicon('person-outline', { fontCharacter: '\\ea67' }) },
    // { id: 'person-filled', defaults: new Codicon('person-filled', { fontCharacter: '\\ea67' }) },
    // { id: 'git-branch', defaults: new Codicon('git-branch', { fontCharacter: '\\ea68' }) },
    // { id: 'git-branch-create', defaults: new Codicon('git-branch-create', { fontCharacter: '\\ea68' }) },
    // { id: 'git-branch-delete', defaults: new Codicon('git-branch-delete', { fontCharacter: '\\ea68' }) },
    // { id: 'source-control', defaults: new Codicon('source-control', { fontCharacter: '\\ea68' }) },
    // { id: 'mirror', defaults: new Codicon('mirror', { fontCharacter: '\\ea69' }) },
    // { id: 'mirror-public', defaults: new Codicon('mirror-public', { fontCharacter: '\\ea69' }) },
    // { id: 'star', defaults: new Codicon('star', { fontCharacter: '\\ea6a' }) },
    // { id: 'star-add', defaults: new Codicon('star-add', { fontCharacter: '\\ea6a' }) },
    // { id: 'star-delete', defaults: new Codicon('star-delete', { fontCharacter: '\\ea6a' }) },
    // { id: 'star-empty', defaults: new Codicon('star-empty', { fontCharacter: '\\ea6a' }) },
    // { id: 'comment', defaults: new Codicon('comment', { fontCharacter: '\\ea6b' }) },
    // { id: 'comment-add', defaults: new Codicon('comment-add', { fontCharacter: '\\ea6b' }) },
    // { id: 'alert', defaults: new Codicon('alert', { fontCharacter: '\\ea6c' }) },
    // { id: 'warning', defaults: new Codicon('warning', { fontCharacter: '\\ea6c' }) },
    // { id: 'search', defaults: new Codicon('search', { fontCharacter: '\\ea6d' }) },
    // { id: 'search-save', defaults: new Codicon('search-save', { fontCharacter: '\\ea6d' }) },
    // { id: 'log-out', defaults: new Codicon('log-out', { fontCharacter: '\\ea6e' }) },
    // { id: 'sign-out', defaults: new Codicon('sign-out', { fontCharacter: '\\ea6e' }) },
    // { id: 'log-in', defaults: new Codicon('log-in', { fontCharacter: '\\ea6f' }) },
    // { id: 'sign-in', defaults: new Codicon('sign-in', { fontCharacter: '\\ea6f' }) },
    // { id: 'eye', defaults: new Codicon('eye', { fontCharacter: '\\ea70' }) },
    // { id: 'eye-unwatch', defaults: new Codicon('eye-unwatch', { fontCharacter: '\\ea70' }) },
    // { id: 'eye-watch', defaults: new Codicon('eye-watch', { fontCharacter: '\\ea70' }) },
    // { id: 'circle-filled', defaults: new Codicon('circle-filled', { fontCharacter: '\\ea71' }) },
    // { id: 'primitive-dot', defaults: new Codicon('primitive-dot', { fontCharacter: '\\ea71' }) },
    // { id: 'close-dirty', defaults: new Codicon('close-dirty', { fontCharacter: '\\ea71' }) },
    // { id: 'debug-breakpoint', defaults: new Codicon('debug-breakpoint', { fontCharacter: '\\ea71' }) },
    // { id: 'debug-breakpoint-disabled', defaults: new Codicon('debug-breakpoint-disabled', { fontCharacter: '\\ea71' }) },
    // { id: 'debug-hint', defaults: new Codicon('debug-hint', { fontCharacter: '\\ea71' }) },
    // { id: 'primitive-square', defaults: new Codicon('primitive-square', { fontCharacter: '\\ea72' }) },
    // { id: 'edit', defaults: new Codicon('edit', { fontCharacter: '\\ea73' }) },
    // { id: 'pencil', defaults: new Codicon('pencil', { fontCharacter: '\\ea73' }) },
    // { id: 'info', defaults: new Codicon('info', { fontCharacter: '\\ea74' }) },
    // { id: 'issue-opened', defaults: new Codicon('issue-opened', { fontCharacter: '\\ea74' }) },
    // { id: 'gist-private', defaults: new Codicon('gist-private', { fontCharacter: '\\ea75' }) },
    // { id: 'git-fork-private', defaults: new Codicon('git-fork-private', { fontCharacter: '\\ea75' }) },
    // { id: 'lock', defaults: new Codicon('lock', { fontCharacter: '\\ea75' }) },
    // { id: 'mirror-private', defaults: new Codicon('mirror-private', { fontCharacter: '\\ea75' }) },
    // { id: 'close', defaults: new Codicon('close', { fontCharacter: '\\ea76' }) },
    // { id: 'remove-close', defaults: new Codicon('remove-close', { fontCharacter: '\\ea76' }) },
    // { id: 'x', defaults: new Codicon('x', { fontCharacter: '\\ea76' }) },
    // { id: 'repo-sync', defaults: new Codicon('repo-sync', { fontCharacter: '\\ea77' }) },
    // { id: 'sync', defaults: new Codicon('sync', { fontCharacter: '\\ea77' }) },
    // { id: 'clone', defaults: new Codicon('clone', { fontCharacter: '\\ea78' }) },
    // { id: 'desktop-download', defaults: new Codicon('desktop-download', { fontCharacter: '\\ea78' }) },
    // { id: 'beaker', defaults: new Codicon('beaker', { fontCharacter: '\\ea79' }) },
    // { id: 'microscope', defaults: new Codicon('microscope', { fontCharacter: '\\ea79' }) },
    // { id: 'vm', defaults: new Codicon('vm', { fontCharacter: '\\ea7a' }) },
    // { id: 'device-desktop', defaults: new Codicon('device-desktop', { fontCharacter: '\\ea7a' }) },
    // { id: 'file', defaults: new Codicon('file', { fontCharacter: '\\ea7b' }) },
    // { id: 'file-text', defaults: new Codicon('file-text', { fontCharacter: '\\ea7b' }) },
    // { id: 'more', defaults: new Codicon('more', { fontCharacter: '\\ea7c' }) },
    // { id: 'ellipsis', defaults: new Codicon('ellipsis', { fontCharacter: '\\ea7c' }) },
    // { id: 'kebab-horizontal', defaults: new Codicon('kebab-horizontal', { fontCharacter: '\\ea7c' }) },
    // { id: 'mail-reply', defaults: new Codicon('mail-reply', { fontCharacter: '\\ea7d' }) },
    // { id: 'reply', defaults: new Codicon('reply', { fontCharacter: '\\ea7d' }) },
    // { id: 'organization', defaults: new Codicon('organization', { fontCharacter: '\\ea7e' }) },
    // { id: 'organization-filled', defaults: new Codicon('organization-filled', { fontCharacter: '\\ea7e' }) },
    // { id: 'organization-outline', defaults: new Codicon('organization-outline', { fontCharacter: '\\ea7e' }) },
    // { id: 'new-file', defaults: new Codicon('new-file', { fontCharacter: '\\ea7f' }) },
    // { id: 'file-add', defaults: new Codicon('file-add', { fontCharacter: '\\ea7f' }) },
    // { id: 'new-folder', defaults: new Codicon('new-folder', { fontCharacter: '\\ea80' }) },
    // { id: 'file-directory-create', defaults: new Codicon('file-directory-create', { fontCharacter: '\\ea80' }) },
    // { id: 'trash', defaults: new Codicon('trash', { fontCharacter: '\\ea81' }) },
    // { id: 'trashcan', defaults: new Codicon('trashcan', { fontCharacter: '\\ea81' }) },
    // { id: 'history', defaults: new Codicon('history', { fontCharacter: '\\ea82' }) },
    // { id: 'clock', defaults: new Codicon('clock', { fontCharacter: '\\ea82' }) },
    // { id: 'folder', defaults: new Codicon('folder', { fontCharacter: '\\ea83' }) },
    // { id: 'file-directory', defaults: new Codicon('file-directory', { fontCharacter: '\\ea83' }) },
    // { id: 'symbol-folder', defaults: new Codicon('symbol-folder', { fontCharacter: '\\ea83' }) },
    // { id: 'logo-github', defaults: new Codicon('logo-github', { fontCharacter: '\\ea84' }) },
    // { id: 'mark-github', defaults: new Codicon('mark-github', { fontCharacter: '\\ea84' }) },
    // { id: 'github', defaults: new Codicon('github', { fontCharacter: '\\ea84' }) },
    // { id: 'terminal', defaults: new Codicon('terminal', { fontCharacter: '\\ea85' }) },
    // { id: 'console', defaults: new Codicon('console', { fontCharacter: '\\ea85' }) },
    // { id: 'repl', defaults: new Codicon('repl', { fontCharacter: '\\ea85' }) },
    // { id: 'zap', defaults: new Codicon('zap', { fontCharacter: '\\ea86' }) },
    // { id: 'symbol-event', defaults: new Codicon('symbol-event', { fontCharacter: '\\ea86' }) },
    // { id: 'error', defaults: new Codicon('error', { fontCharacter: '\\ea87' }) },
    // { id: 'stop', defaults: new Codicon('stop', { fontCharacter: '\\ea87' }) },
    // { id: 'variable', defaults: new Codicon('variable', { fontCharacter: '\\ea88' }) },
    // { id: 'symbol-variable', defaults: new Codicon('symbol-variable', { fontCharacter: '\\ea88' }) },
    // { id: 'array', defaults: new Codicon('array', { fontCharacter: '\\ea8a' }) },
    // { id: 'symbol-array', defaults: new Codicon('symbol-array', { fontCharacter: '\\ea8a' }) },
    // { id: 'symbol-module', defaults: new Codicon('symbol-module', { fontCharacter: '\\ea8b' }) },
    // { id: 'symbol-package', defaults: new Codicon('symbol-package', { fontCharacter: '\\ea8b' }) },
    // { id: 'symbol-namespace', defaults: new Codicon('symbol-namespace', { fontCharacter: '\\ea8b' }) },
    // { id: 'symbol-object', defaults: new Codicon('symbol-object', { fontCharacter: '\\ea8b' }) },
    // { id: 'symbol-method', defaults: new Codicon('symbol-method', { fontCharacter: '\\ea8c' }) },
    // { id: 'symbol-function', defaults: new Codicon('symbol-function', { fontCharacter: '\\ea8c' }) },
    // { id: 'symbol-constructor', defaults: new Codicon('symbol-constructor', { fontCharacter: '\\ea8c' }) },
    // { id: 'symbol-boolean', defaults: new Codicon('symbol-boolean', { fontCharacter: '\\ea8f' }) },
    // { id: 'symbol-null', defaults: new Codicon('symbol-null', { fontCharacter: '\\ea8f' }) },
    // { id: 'symbol-numeric', defaults: new Codicon('symbol-numeric', { fontCharacter: '\\ea90' }) },
    // { id: 'symbol-number', defaults: new Codicon('symbol-number', { fontCharacter: '\\ea90' }) },
    // { id: 'symbol-structure', defaults: new Codicon('symbol-structure', { fontCharacter: '\\ea91' }) },
    // { id: 'symbol-struct', defaults: new Codicon('symbol-struct', { fontCharacter: '\\ea91' }) },
    // { id: 'symbol-parameter', defaults: new Codicon('symbol-parameter', { fontCharacter: '\\ea92' }) },
    // { id: 'symbol-type-parameter', defaults: new Codicon('symbol-type-parameter', { fontCharacter: '\\ea92' }) },
    // { id: 'symbol-key', defaults: new Codicon('symbol-key', { fontCharacter: '\\ea93' }) },
    // { id: 'symbol-text', defaults: new Codicon('symbol-text', { fontCharacter: '\\ea93' }) },
    // { id: 'symbol-reference', defaults: new Codicon('symbol-reference', { fontCharacter: '\\ea94' }) },
    // { id: 'go-to-file', defaults: new Codicon('go-to-file', { fontCharacter: '\\ea94' }) },
    // { id: 'symbol-enum', defaults: new Codicon('symbol-enum', { fontCharacter: '\\ea95' }) },
    // { id: 'symbol-value', defaults: new Codicon('symbol-value', { fontCharacter: '\\ea95' }) },
    // { id: 'symbol-ruler', defaults: new Codicon('symbol-ruler', { fontCharacter: '\\ea96' }) },
    // { id: 'symbol-unit', defaults: new Codicon('symbol-unit', { fontCharacter: '\\ea96' }) },
    // { id: 'activate-breakpoints', defaults: new Codicon('activate-breakpoints', { fontCharacter: '\\ea97' }) },
    // { id: 'archive', defaults: new Codicon('archive', { fontCharacter: '\\ea98' }) },
    // { id: 'arrow-both', defaults: new Codicon('arrow-both', { fontCharacter: '\\ea99' }) },
    // { id: 'arrow-down', defaults: new Codicon('arrow-down', { fontCharacter: '\\ea9a' }) },
    // { id: 'arrow-left', defaults: new Codicon('arrow-left', { fontCharacter: '\\ea9b' }) },
    // { id: 'arrow-right', defaults: new Codicon('arrow-right', { fontCharacter: '\\ea9c' }) },
    // { id: 'arrow-small-down', defaults: new Codicon('arrow-small-down', { fontCharacter: '\\ea9d' }) },
    // { id: 'arrow-small-left', defaults: new Codicon('arrow-small-left', { fontCharacter: '\\ea9e' }) },
    // { id: 'arrow-small-right', defaults: new Codicon('arrow-small-right', { fontCharacter: '\\ea9f' }) },
    // { id: 'arrow-small-up', defaults: new Codicon('arrow-small-up', { fontCharacter: '\\eaa0' }) },
    // { id: 'arrow-up', defaults: new Codicon('arrow-up', { fontCharacter: '\\eaa1' }) },
    // { id: 'bell', defaults: new Codicon('bell', { fontCharacter: '\\eaa2' }) },
    // { id: 'bold', defaults: new Codicon('bold', { fontCharacter: '\\eaa3' }) },
    // { id: 'book', defaults: new Codicon('book', { fontCharacter: '\\eaa4' }) },
    // { id: 'bookmark', defaults: new Codicon('bookmark', { fontCharacter: '\\eaa5' }) },
    // { id: 'debug-breakpoint-conditional-unverified', defaults: new Codicon('debug-breakpoint-conditional-unverified', { fontCharacter: '\\eaa6' }) },
    // { id: 'debug-breakpoint-conditional', defaults: new Codicon('debug-breakpoint-conditional', { fontCharacter: '\\eaa7' }) },
    // { id: 'debug-breakpoint-conditional-disabled', defaults: new Codicon('debug-breakpoint-conditional-disabled', { fontCharacter: '\\eaa7' }) },
    // { id: 'debug-breakpoint-data-unverified', defaults: new Codicon('debug-breakpoint-data-unverified', { fontCharacter: '\\eaa8' }) },
    // { id: 'debug-breakpoint-data', defaults: new Codicon('debug-breakpoint-data', { fontCharacter: '\\eaa9' }) },
    // { id: 'debug-breakpoint-data-disabled', defaults: new Codicon('debug-breakpoint-data-disabled', { fontCharacter: '\\eaa9' }) },
    // { id: 'debug-breakpoint-log-unverified', defaults: new Codicon('debug-breakpoint-log-unverified', { fontCharacter: '\\eaaa' }) },
    // { id: 'debug-breakpoint-log', defaults: new Codicon('debug-breakpoint-log', { fontCharacter: '\\eaab' }) },
    // { id: 'debug-breakpoint-log-disabled', defaults: new Codicon('debug-breakpoint-log-disabled', { fontCharacter: '\\eaab' }) },
    // { id: 'briefcase', defaults: new Codicon('briefcase', { fontCharacter: '\\eaac' }) },
    // { id: 'broadcast', defaults: new Codicon('broadcast', { fontCharacter: '\\eaad' }) },
    // { id: 'browser', defaults: new Codicon('browser', { fontCharacter: '\\eaae' }) },
    // { id: 'bug', defaults: new Codicon('bug', { fontCharacter: '\\eaaf' }) },
    // { id: 'calendar', defaults: new Codicon('calendar', { fontCharacter: '\\eab0' }) },
    // { id: 'case-sensitive', defaults: new Codicon('case-sensitive', { fontCharacter: '\\eab1' }) },
    // { id: 'check', defaults: new Codicon('check', { fontCharacter: '\\eab2' }) },
    // { id: 'checklist', defaults: new Codicon('checklist', { fontCharacter: '\\eab3' }) },
    // { id: 'chevron-down', defaults: new Codicon('chevron-down', { fontCharacter: '\\eab4' }) },
    // { id: 'chevron-left', defaults: new Codicon('chevron-left', { fontCharacter: '\\eab5' }) },
    // { id: 'chevron-right', defaults: new Codicon('chevron-right', { fontCharacter: '\\eab6' }) },
    // { id: 'chevron-up', defaults: new Codicon('chevron-up', { fontCharacter: '\\eab7' }) },
    // { id: 'chrome-close', defaults: new Codicon('chrome-close', { fontCharacter: '\\eab8' }) },
    // { id: 'chrome-maximize', defaults: new Codicon('chrome-maximize', { fontCharacter: '\\eab9' }) },
    // { id: 'chrome-minimize', defaults: new Codicon('chrome-minimize', { fontCharacter: '\\eaba' }) },
    // { id: 'chrome-restore', defaults: new Codicon('chrome-restore', { fontCharacter: '\\eabb' }) },
    // { id: 'circle-outline', defaults: new Codicon('circle-outline', { fontCharacter: '\\eabc' }) },
    // { id: 'debug-breakpoint-unverified', defaults: new Codicon('debug-breakpoint-unverified', { fontCharacter: '\\eabc' }) },
    // { id: 'circle-slash', defaults: new Codicon('circle-slash', { fontCharacter: '\\eabd' }) },
    // { id: 'circuit-board', defaults: new Codicon('circuit-board', { fontCharacter: '\\eabe' }) },
    // { id: 'clear-all', defaults: new Codicon('clear-all', { fontCharacter: '\\eabf' }) },
    // { id: 'clippy', defaults: new Codicon('clippy', { fontCharacter: '\\eac0' }) },
    // { id: 'close-all', defaults: new Codicon('close-all', { fontCharacter: '\\eac1' }) },
    // { id: 'cloud-download', defaults: new Codicon('cloud-download', { fontCharacter: '\\eac2' }) },
    // { id: 'cloud-upload', defaults: new Codicon('cloud-upload', { fontCharacter: '\\eac3' }) },
    // { id: 'code', defaults: new Codicon('code', { fontCharacter: '\\eac4' }) },
    // { id: 'collapse-all', defaults: new Codicon('collapse-all', { fontCharacter: '\\eac5' }) },
    // { id: 'color-mode', defaults: new Codicon('color-mode', { fontCharacter: '\\eac6' }) },
    // { id: 'comment-discussion', defaults: new Codicon('comment-discussion', { fontCharacter: '\\eac7' }) },
    // { id: 'compare-changes', defaults: new Codicon('compare-changes', { fontCharacter: '\\eafd' }) },
    // { id: 'credit-card', defaults: new Codicon('credit-card', { fontCharacter: '\\eac9' }) },
    // { id: 'dash', defaults: new Codicon('dash', { fontCharacter: '\\eacc' }) },
    // { id: 'dashboard', defaults: new Codicon('dashboard', { fontCharacter: '\\eacd' }) },
    // { id: 'database', defaults: new Codicon('database', { fontCharacter: '\\eace' }) },
    // { id: 'debug-continue', defaults: new Codicon('debug-continue', { fontCharacter: '\\eacf' }) },
    // { id: 'debug-disconnect', defaults: new Codicon('debug-disconnect', { fontCharacter: '\\ead0' }) },
    // { id: 'debug-pause', defaults: new Codicon('debug-pause', { fontCharacter: '\\ead1' }) },
    // { id: 'debug-restart', defaults: new Codicon('debug-restart', { fontCharacter: '\\ead2' }) },
    // { id: 'debug-start', defaults: new Codicon('debug-start', { fontCharacter: '\\ead3' }) },
    // { id: 'debug-step-into', defaults: new Codicon('debug-step-into', { fontCharacter: '\\ead4' }) },
    // { id: 'debug-step-out', defaults: new Codicon('debug-step-out', { fontCharacter: '\\ead5' }) },
    // { id: 'debug-step-over', defaults: new Codicon('debug-step-over', { fontCharacter: '\\ead6' }) },
    // { id: 'debug-stop', defaults: new Codicon('debug-stop', { fontCharacter: '\\ead7' }) },
    // { id: 'debug', defaults: new Codicon('debug', { fontCharacter: '\\ead8' }) },
    // { id: 'device-camera-video', defaults: new Codicon('device-camera-video', { fontCharacter: '\\ead9' }) },
    // { id: 'device-camera', defaults: new Codicon('device-camera', { fontCharacter: '\\eada' }) },
    // { id: 'device-mobile', defaults: new Codicon('device-mobile', { fontCharacter: '\\eadb' }) },
    // { id: 'diff-added', defaults: new Codicon('diff-added', { fontCharacter: '\\eadc' }) },
    // { id: 'diff-ignored', defaults: new Codicon('diff-ignored', { fontCharacter: '\\eadd' }) },
    // { id: 'diff-modified', defaults: new Codicon('diff-modified', { fontCharacter: '\\eade' }) },
    // { id: 'diff-removed', defaults: new Codicon('diff-removed', { fontCharacter: '\\eadf' }) },
    // { id: 'diff-renamed', defaults: new Codicon('diff-renamed', { fontCharacter: '\\eae0' }) },
    // { id: 'diff', defaults: new Codicon('diff', { fontCharacter: '\\eae1' }) },
    // { id: 'discard', defaults: new Codicon('discard', { fontCharacter: '\\eae2' }) },
    // { id: 'editor-layout', defaults: new Codicon('editor-layout', { fontCharacter: '\\eae3' }) },
    // { id: 'empty-window', defaults: new Codicon('empty-window', { fontCharacter: '\\eae4' }) },
    // { id: 'exclude', defaults: new Codicon('exclude', { fontCharacter: '\\eae5' }) },
    // { id: 'extensions', defaults: new Codicon('extensions', { fontCharacter: '\\eae6' }) },
    // { id: 'eye-closed', defaults: new Codicon('eye-closed', { fontCharacter: '\\eae7' }) },
    // { id: 'file-binary', defaults: new Codicon('file-binary', { fontCharacter: '\\eae8' }) },
    // { id: 'file-code', defaults: new Codicon('file-code', { fontCharacter: '\\eae9' }) },
    // { id: 'file-media', defaults: new Codicon('file-media', { fontCharacter: '\\eaea' }) },
    // { id: 'file-pdf', defaults: new Codicon('file-pdf', { fontCharacter: '\\eaeb' }) },
    // { id: 'file-submodule', defaults: new Codicon('file-submodule', { fontCharacter: '\\eaec' }) },
    // { id: 'file-symlink-directory', defaults: new Codicon('file-symlink-directory', { fontCharacter: '\\eaed' }) },
    // { id: 'file-symlink-file', defaults: new Codicon('file-symlink-file', { fontCharacter: '\\eaee' }) },
    // { id: 'file-zip', defaults: new Codicon('file-zip', { fontCharacter: '\\eaef' }) },
    // { id: 'files', defaults: new Codicon('files', { fontCharacter: '\\eaf0' }) },
    // { id: 'filter', defaults: new Codicon('filter', { fontCharacter: '\\eaf1' }) },
    // { id: 'flame', defaults: new Codicon('flame', { fontCharacter: '\\eaf2' }) },
    // { id: 'fold-down', defaults: new Codicon('fold-down', { fontCharacter: '\\eaf3' }) },
    // { id: 'fold-up', defaults: new Codicon('fold-up', { fontCharacter: '\\eaf4' }) },
    // { id: 'fold', defaults: new Codicon('fold', { fontCharacter: '\\eaf5' }) },
    // { id: 'folder-active', defaults: new Codicon('folder-active', { fontCharacter: '\\eaf6' }) },
    // { id: 'folder-opened', defaults: new Codicon('folder-opened', { fontCharacter: '\\eaf7' }) },
    // { id: 'gear', defaults: new Codicon('gear', { fontCharacter: '\\eaf8' }) },
    // { id: 'gift', defaults: new Codicon('gift', { fontCharacter: '\\eaf9' }) },
    // { id: 'gist-secret', defaults: new Codicon('gist-secret', { fontCharacter: '\\eafa' }) },
    // { id: 'gist', defaults: new Codicon('gist', { fontCharacter: '\\eafb' }) },
    // { id: 'git-commit', defaults: new Codicon('git-commit', { fontCharacter: '\\eafc' }) },
    // { id: 'git-compare', defaults: new Codicon('git-compare', { fontCharacter: '\\eafd' }) },
    // { id: 'git-merge', defaults: new Codicon('git-merge', { fontCharacter: '\\eafe' }) },
    // { id: 'github-action', defaults: new Codicon('github-action', { fontCharacter: '\\eaff' }) },
    // { id: 'github-alt', defaults: new Codicon('github-alt', { fontCharacter: '\\eb00' }) },
    // { id: 'globe', defaults: new Codicon('globe', { fontCharacter: '\\eb01' }) },
    // { id: 'grabber', defaults: new Codicon('grabber', { fontCharacter: '\\eb02' }) },
    // { id: 'graph', defaults: new Codicon('graph', { fontCharacter: '\\eb03' }) },
    // { id: 'gripper', defaults: new Codicon('gripper', { fontCharacter: '\\eb04' }) },
    // { id: 'heart', defaults: new Codicon('heart', { fontCharacter: '\\eb05' }) },
    // { id: 'home', defaults: new Codicon('home', { fontCharacter: '\\eb06' }) },
    // { id: 'horizontal-rule', defaults: new Codicon('horizontal-rule', { fontCharacter: '\\eb07' }) },
    // { id: 'hubot', defaults: new Codicon('hubot', { fontCharacter: '\\eb08' }) },
    // { id: 'inbox', defaults: new Codicon('inbox', { fontCharacter: '\\eb09' }) },
    // { id: 'issue-closed', defaults: new Codicon('issue-closed', { fontCharacter: '\\eb0a' }) },
    // { id: 'issue-reopened', defaults: new Codicon('issue-reopened', { fontCharacter: '\\eb0b' }) },
    // { id: 'issues', defaults: new Codicon('issues', { fontCharacter: '\\eb0c' }) },
    // { id: 'italic', defaults: new Codicon('italic', { fontCharacter: '\\eb0d' }) },
    // { id: 'jersey', defaults: new Codicon('jersey', { fontCharacter: '\\eb0e' }) },
    // { id: 'json', defaults: new Codicon('json', { fontCharacter: '\\eb0f' }) },
    // { id: 'kebab-vertical', defaults: new Codicon('kebab-vertical', { fontCharacter: '\\eb10' }) },
    // { id: 'key', defaults: new Codicon('key', { fontCharacter: '\\eb11' }) },
    // { id: 'law', defaults: new Codicon('law', { fontCharacter: '\\eb12' }) },
    // { id: 'lightbulb-autofix', defaults: new Codicon('lightbulb-autofix', { fontCharacter: '\\eb13' }) },
    // { id: 'link-external', defaults: new Codicon('link-external', { fontCharacter: '\\eb14' }) },
    // { id: 'link', defaults: new Codicon('link', { fontCharacter: '\\eb15' }) },
    // { id: 'list-ordered', defaults: new Codicon('list-ordered', { fontCharacter: '\\eb16' }) },
    // { id: 'list-unordered', defaults: new Codicon('list-unordered', { fontCharacter: '\\eb17' }) },
    // { id: 'live-share', defaults: new Codicon('live-share', { fontCharacter: '\\eb18' }) },
    // { id: 'loading', defaults: new Codicon('loading', { fontCharacter: '\\eb19' }) },
    // { id: 'location', defaults: new Codicon('location', { fontCharacter: '\\eb1a' }) },
    // { id: 'mail-read', defaults: new Codicon('mail-read', { fontCharacter: '\\eb1b' }) },
    // { id: 'mail', defaults: new Codicon('mail', { fontCharacter: '\\eb1c' }) },
    // { id: 'markdown', defaults: new Codicon('markdown', { fontCharacter: '\\eb1d' }) },
    // { id: 'megaphone', defaults: new Codicon('megaphone', { fontCharacter: '\\eb1e' }) },
    // { id: 'mention', defaults: new Codicon('mention', { fontCharacter: '\\eb1f' }) },
    // { id: 'milestone', defaults: new Codicon('milestone', { fontCharacter: '\\eb20' }) },
    // { id: 'mortar-board', defaults: new Codicon('mortar-board', { fontCharacter: '\\eb21' }) },
    // { id: 'move', defaults: new Codicon('move', { fontCharacter: '\\eb22' }) },
    // { id: 'multiple-windows', defaults: new Codicon('multiple-windows', { fontCharacter: '\\eb23' }) },
    // { id: 'mute', defaults: new Codicon('mute', { fontCharacter: '\\eb24' }) },
    // { id: 'no-newline', defaults: new Codicon('no-newline', { fontCharacter: '\\eb25' }) },
    // { id: 'note', defaults: new Codicon('note', { fontCharacter: '\\eb26' }) },
    // { id: 'octoface', defaults: new Codicon('octoface', { fontCharacter: '\\eb27' }) },
    // { id: 'open-preview', defaults: new Codicon('open-preview', { fontCharacter: '\\eb28' }) },
    // { id: 'package', defaults: new Codicon('package', { fontCharacter: '\\eb29' }) },
    // { id: 'paintcan', defaults: new Codicon('paintcan', { fontCharacter: '\\eb2a' }) },
    // { id: 'pin', defaults: new Codicon('pin', { fontCharacter: '\\eb2b' }) },
    // { id: 'play', defaults: new Codicon('play', { fontCharacter: '\\eb2c' }) },
    // { id: 'run', defaults: new Codicon('run', { fontCharacter: '\\eb2c' }) },
    // { id: 'plug', defaults: new Codicon('plug', { fontCharacter: '\\eb2d' }) },
    // { id: 'preserve-case', defaults: new Codicon('preserve-case', { fontCharacter: '\\eb2e' }) },
    // { id: 'preview', defaults: new Codicon('preview', { fontCharacter: '\\eb2f' }) },
    // { id: 'project', defaults: new Codicon('project', { fontCharacter: '\\eb30' }) },
    // { id: 'pulse', defaults: new Codicon('pulse', { fontCharacter: '\\eb31' }) },
    // { id: 'question', defaults: new Codicon('question', { fontCharacter: '\\eb32' }) },
    // { id: 'quote', defaults: new Codicon('quote', { fontCharacter: '\\eb33' }) },
    // { id: 'radio-tower', defaults: new Codicon('radio-tower', { fontCharacter: '\\eb34' }) },
    // { id: 'reactions', defaults: new Codicon('reactions', { fontCharacter: '\\eb35' }) },
    // { id: 'references', defaults: new Codicon('references', { fontCharacter: '\\eb36' }) },
    // { id: 'refresh', defaults: new Codicon('refresh', { fontCharacter: '\\eb37' }) },
    // { id: 'regex', defaults: new Codicon('regex', { fontCharacter: '\\eb38' }) },
    // { id: 'remote-explorer', defaults: new Codicon('remote-explorer', { fontCharacter: '\\eb39' }) },
    // { id: 'remote', defaults: new Codicon('remote', { fontCharacter: '\\eb3a' }) },
    // { id: 'remove', defaults: new Codicon('remove', { fontCharacter: '\\eb3b' }) },
    // { id: 'replace-all', defaults: new Codicon('replace-all', { fontCharacter: '\\eb3c' }) },
    // { id: 'replace', defaults: new Codicon('replace', { fontCharacter: '\\eb3d' }) },
    // { id: 'repo-clone', defaults: new Codicon('repo-clone', { fontCharacter: '\\eb3e' }) },
    // { id: 'repo-force-push', defaults: new Codicon('repo-force-push', { fontCharacter: '\\eb3f' }) },
    // { id: 'repo-pull', defaults: new Codicon('repo-pull', { fontCharacter: '\\eb40' }) },
    // { id: 'repo-push', defaults: new Codicon('repo-push', { fontCharacter: '\\eb41' }) },
    // { id: 'report', defaults: new Codicon('report', { fontCharacter: '\\eb42' }) },
    // { id: 'request-changes', defaults: new Codicon('request-changes', { fontCharacter: '\\eb43' }) },
    // { id: 'rocket', defaults: new Codicon('rocket', { fontCharacter: '\\eb44' }) },
    // { id: 'root-folder-opened', defaults: new Codicon('root-folder-opened', { fontCharacter: '\\eb45' }) },
    // { id: 'root-folder', defaults: new Codicon('root-folder', { fontCharacter: '\\eb46' }) },
    // { id: 'rss', defaults: new Codicon('rss', { fontCharacter: '\\eb47' }) },
    // { id: 'ruby', defaults: new Codicon('ruby', { fontCharacter: '\\eb48' }) },
    // { id: 'save-all', defaults: new Codicon('save-all', { fontCharacter: '\\eb49' }) },
    // { id: 'save-as', defaults: new Codicon('save-as', { fontCharacter: '\\eb4a' }) },
    // { id: 'save', defaults: new Codicon('save', { fontCharacter: '\\eb4b' }) },
    // { id: 'screen-full', defaults: new Codicon('screen-full', { fontCharacter: '\\eb4c' }) },
    // { id: 'screen-normal', defaults: new Codicon('screen-normal', { fontCharacter: '\\eb4d' }) },
    // { id: 'search-stop', defaults: new Codicon('search-stop', { fontCharacter: '\\eb4e' }) },
    // { id: 'server', defaults: new Codicon('server', { fontCharacter: '\\eb50' }) },
    // { id: 'settings-gear', defaults: new Codicon('settings-gear', { fontCharacter: '\\eb51' }) },
    // { id: 'settings', defaults: new Codicon('settings', { fontCharacter: '\\eb52' }) },
    // { id: 'shield', defaults: new Codicon('shield', { fontCharacter: '\\eb53' }) },
    // { id: 'smiley', defaults: new Codicon('smiley', { fontCharacter: '\\eb54' }) },
    // { id: 'sort-precedence', defaults: new Codicon('sort-precedence', { fontCharacter: '\\eb55' }) },
    // { id: 'split-horizontal', defaults: new Codicon('split-horizontal', { fontCharacter: '\\eb56' }) },
    // { id: 'split-vertical', defaults: new Codicon('split-vertical', { fontCharacter: '\\eb57' }) },
    // { id: 'squirrel', defaults: new Codicon('squirrel', { fontCharacter: '\\eb58' }) },
    // { id: 'star-full', defaults: new Codicon('star-full', { fontCharacter: '\\eb59' }) },
    // { id: 'star-half', defaults: new Codicon('star-half', { fontCharacter: '\\eb5a' }) },
    // { id: 'symbol-class', defaults: new Codicon('symbol-class', { fontCharacter: '\\eb5b' }) },
    // { id: 'symbol-color', defaults: new Codicon('symbol-color', { fontCharacter: '\\eb5c' }) },
    // { id: 'symbol-constant', defaults: new Codicon('symbol-constant', { fontCharacter: '\\eb5d' }) },
    // { id: 'symbol-enum-member', defaults: new Codicon('symbol-enum-member', { fontCharacter: '\\eb5e' }) },
    // { id: 'symbol-field', defaults: new Codicon('symbol-field', { fontCharacter: '\\eb5f' }) },
    // { id: 'symbol-file', defaults: new Codicon('symbol-file', { fontCharacter: '\\eb60' }) },
    // { id: 'symbol-interface', defaults: new Codicon('symbol-interface', { fontCharacter: '\\eb61' }) },
    // { id: 'symbol-keyword', defaults: new Codicon('symbol-keyword', { fontCharacter: '\\eb62' }) },
    // { id: 'symbol-misc', defaults: new Codicon('symbol-misc', { fontCharacter: '\\eb63' }) },
    // { id: 'symbol-operator', defaults: new Codicon('symbol-operator', { fontCharacter: '\\eb64' }) },
    // { id: 'symbol-property', defaults: new Codicon('symbol-property', { fontCharacter: '\\eb65' }) },
    // { id: 'wrench', defaults: new Codicon('wrench', { fontCharacter: '\\eb65' }) },
    // { id: 'wrench-subaction', defaults: new Codicon('wrench-subaction', { fontCharacter: '\\eb65' }) },
    // { id: 'symbol-snippet', defaults: new Codicon('symbol-snippet', { fontCharacter: '\\eb66' }) },
    // { id: 'tasklist', defaults: new Codicon('tasklist', { fontCharacter: '\\eb67' }) },
    // { id: 'telescope', defaults: new Codicon('telescope', { fontCharacter: '\\eb68' }) },
    // { id: 'text-size', defaults: new Codicon('text-size', { fontCharacter: '\\eb69' }) },
    // { id: 'three-bars', defaults: new Codicon('three-bars', { fontCharacter: '\\eb6a' }) },
    // { id: 'thumbsdown', defaults: new Codicon('thumbsdown', { fontCharacter: '\\eb6b' }) },
    // { id: 'thumbsup', defaults: new Codicon('thumbsup', { fontCharacter: '\\eb6c' }) },
    // { id: 'tools', defaults: new Codicon('tools', { fontCharacter: '\\eb6d' }) },
    // { id: 'triangle-down', defaults: new Codicon('triangle-down', { fontCharacter: '\\eb6e' }) },
    // { id: 'triangle-left', defaults: new Codicon('triangle-left', { fontCharacter: '\\eb6f' }) },
    // { id: 'triangle-right', defaults: new Codicon('triangle-right', { fontCharacter: '\\eb70' }) },
    // { id: 'triangle-up', defaults: new Codicon('triangle-up', { fontCharacter: '\\eb71' }) },
    // { id: 'twitter', defaults: new Codicon('twitter', { fontCharacter: '\\eb72' }) },
    // { id: 'unfold', defaults: new Codicon('unfold', { fontCharacter: '\\eb73' }) },
    // { id: 'unlock', defaults: new Codicon('unlock', { fontCharacter: '\\eb74' }) },
    // { id: 'unmute', defaults: new Codicon('unmute', { fontCharacter: '\\eb75' }) },
    // { id: 'unverified', defaults: new Codicon('unverified', { fontCharacter: '\\eb76' }) },
    // { id: 'verified', defaults: new Codicon('verified', { fontCharacter: '\\eb77' }) },
    // { id: 'versions', defaults: new Codicon('versions', { fontCharacter: '\\eb78' }) },
    // { id: 'vm-active', defaults: new Codicon('vm-active', { fontCharacter: '\\eb79' }) },
    // { id: 'vm-outline', defaults: new Codicon('vm-outline', { fontCharacter: '\\eb7a' }) },
    // { id: 'vm-running', defaults: new Codicon('vm-running', { fontCharacter: '\\eb7b' }) },
    // { id: 'watch', defaults: new Codicon('watch', { fontCharacter: '\\eb7c' }) },
    // { id: 'whitespace', defaults: new Codicon('whitespace', { fontCharacter: '\\eb7d' }) },
    // { id: 'whole-word', defaults: new Codicon('whole-word', { fontCharacter: '\\eb7e' }) },
    // { id: 'window', defaults: new Codicon('window', { fontCharacter: '\\eb7f' }) },
    // { id: 'word-wrap', defaults: new Codicon('word-wrap', { fontCharacter: '\\eb80' }) },
    // { id: 'zoom-in', defaults: new Codicon('zoom-in', { fontCharacter: '\\eb81' }) },
    // { id: 'zoom-out', defaults: new Codicon('zoom-out', { fontCharacter: '\\eb82' }) },
    // { id: 'list-filter', defaults: new Codicon('list-filter', { fontCharacter: '\\eb83' }) },
    // { id: 'list-flat', defaults: new Codicon('list-flat', { fontCharacter: '\\eb84' }) },
    // { id: 'list-selection', defaults: new Codicon('list-selection', { fontCharacter: '\\eb85' }) },
    // { id: 'selection', defaults: new Codicon('selection', { fontCharacter: '\\eb85' }) },
    // { id: 'list-tree', defaults: new Codicon('list-tree', { fontCharacter: '\\eb86' }) },
    // { id: 'debug-breakpoint-function-unverified', defaults: new Codicon('debug-breakpoint-function-unverified', { fontCharacter: '\\eb87' }) },
    // { id: 'debug-breakpoint-function', defaults: new Codicon('debug-breakpoint-function', { fontCharacter: '\\eb88' }) },
    // { id: 'debug-breakpoint-function-disabled', defaults: new Codicon('debug-breakpoint-function-disabled', { fontCharacter: '\\eb88' }) },
    // { id: 'debug-stackframe-active', defaults: new Codicon('debug-stackframe-active', { fontCharacter: '\\eb89' }) },
    // { id: 'debug-stackframe-dot', defaults: new Codicon('debug-stackframe-dot', { fontCharacter: '\\eb8a' }) },
    // { id: 'debug-stackframe', defaults: new Codicon('debug-stackframe', { fontCharacter: '\\eb8b' }) },
    // { id: 'debug-stackframe-focused', defaults: new Codicon('debug-stackframe-focused', { fontCharacter: '\\eb8b' }) },
    // { id: 'debug-breakpoint-unsupported', defaults: new Codicon('debug-breakpoint-unsupported', { fontCharacter: '\\eb8c' }) },
    // { id: 'symbol-string', defaults: new Codicon('symbol-string', { fontCharacter: '\\eb8d' }) },
    // { id: 'debug-reverse-continue', defaults: new Codicon('debug-reverse-continue', { fontCharacter: '\\eb8e' }) },
    // { id: 'debug-step-back', defaults: new Codicon('debug-step-back', { fontCharacter: '\\eb8f' }) },
    // { id: 'debug-restart-frame', defaults: new Codicon('debug-restart-frame', { fontCharacter: '\\eb90' }) },
    // { id: 'call-incoming', defaults: new Codicon('call-incoming', { fontCharacter: '\\eb92' }) },
    // { id: 'call-outgoing', defaults: new Codicon('call-outgoing', { fontCharacter: '\\eb93' }) },
    // { id: 'menu', defaults: new Codicon('menu', { fontCharacter: '\\eb94' }) },
    // { id: 'expand-all', defaults: new Codicon('expand-all', { fontCharacter: '\\eb95' }) },
    // { id: 'feedback', defaults: new Codicon('feedback', { fontCharacter: '\\eb96' }) },
    // { id: 'group-by-ref-type', defaults: new Codicon('group-by-ref-type', { fontCharacter: '\\eb97' }) },
    // { id: 'ungroup-by-ref-type', defaults: new Codicon('ungroup-by-ref-type', { fontCharacter: '\\eb98' }) },
    // { id: 'account', defaults: new Codicon('account', { fontCharacter: '\\eb99' }) },
    // { id: 'bell-dot', defaults: new Codicon('bell-dot', { fontCharacter: '\\eb9a' }) },
    // { id: 'debug-console', defaults: new Codicon('debug-console', { fontCharacter: '\\eb9b' }) },
    // { id: 'library', defaults: new Codicon('library', { fontCharacter: '\\eb9c' }) },
    // { id: 'output', defaults: new Codicon('output', { fontCharacter: '\\eb9d' }) },
    // { id: 'run-all', defaults: new Codicon('run-all', { fontCharacter: '\\eb9e' }) },
    // { id: 'sync-ignored', defaults: new Codicon('sync-ignored', { fontCharacter: '\\eb9f' }) },
    // { id: 'pinned', defaults: new Codicon('pinned', { fontCharacter: '\\eba0' }) },
    // { id: 'github-inverted', defaults: new Codicon('github-inverted', { fontCharacter: '\\eba1' }) },
    // { id: 'debug-alt', defaults: new Codicon('debug-alt', { fontCharacter: '\\eb91' }) },
    // { id: 'server-process', defaults: new Codicon('server-process', { fontCharacter: '\\eba2' }) },
    // { id: 'server-environment', defaults: new Codicon('server-environment', { fontCharacter: '\\eba3' }) },
    // { id: 'pass', defaults: new Codicon('pass', { fontCharacter: '\\eba4' }) },
    // { id: 'stop-circle', defaults: new Codicon('stop-circle', { fontCharacter: '\\eba5' }) },
    // { id: 'play-circle', defaults: new Codicon('play-circle', { fontCharacter: '\\eba6' }) },
    // { id: 'record', defaults: new Codicon('record', { fontCharacter: '\\eba7' }) },
    // { id: 'debug-alt-small', defaults: new Codicon('debug-alt-small', { fontCharacter: '\\eba8' }) },
    // { id: 'vm-connect', defaults: new Codicon('vm-connect', { fontCharacter: '\\eba9' }) },
    // { id: 'cloud', defaults: new Codicon('cloud', { fontCharacter: '\\ebaa' }) },
    // { id: 'merge', defaults: new Codicon('merge', { fontCharacter: '\\ebab' }) },
    // { id: 'export', defaults: new Codicon('export', { fontCharacter: '\\ebac' }) },
    // { id: 'graph-left', defaults: new Codicon('graph-left', { fontCharacter: '\\ebad' }) },
    // { id: 'magnet', defaults: new Codicon('magnet', { fontCharacter: '\\ebae' }) },
    // { id: 'notebook', defaults: new Codicon('notebook', { fontCharacter: '\\ebaf' }) },
    // { id: 'redo', defaults: new Codicon('redo', { fontCharacter: '\\ebb0' }) },
    // { id: 'check-all', defaults: new Codicon('check-all', { fontCharacter: '\\ebb1' }) },
    // { id: 'pinned-dirty', defaults: new Codicon('pinned-dirty', { fontCharacter: '\\ebb2' }) },
    // { id: 'pass-filled', defaults: new Codicon('pass-filled', { fontCharacter: '\\ebb3' }) },
    // { id: 'circle-large-filled', defaults: new Codicon('circle-large-filled', { fontCharacter: '\\ebb4' }) },
    // { id: 'circle-large-outline', defaults: new Codicon('circle-large-outline', { fontCharacter: '\\ebb5' }) },
    // { id: 'combine', defaults: new Codicon('combine', { fontCharacter: '\\ebb6' }) },
    // { id: 'gather', defaults: new Codicon('gather', { fontCharacter: '\\ebb6' }) },
    // { id: 'table', defaults: new Codicon('table', { fontCharacter: '\\ebb7' }) },
    // { id: 'variable-group', defaults: new Codicon('variable-group', { fontCharacter: '\\ebb8' }) },
    // { id: 'type-hierarchy', defaults: new Codicon('type-hierarchy', { fontCharacter: '\\ebb9' }) },
    // { id: 'type-hierarchy-sub', defaults: new Codicon('type-hierarchy-sub', { fontCharacter: '\\ebba' }) },
    // { id: 'type-hierarchy-super', defaults: new Codicon('type-hierarchy-super', { fontCharacter: '\\ebbb' }) },
    // { id: 'git-pull-request-create', defaults: new Codicon('git-pull-request-create', { fontCharacter: '\\ebbc' }) },
    // { id: 'run-above', defaults: new Codicon('run-above', { fontCharacter: '\\ebbd' }) },
    // { id: 'run-below', defaults: new Codicon('run-below', { fontCharacter: '\\ebbe' }) },
    // { id: 'notebook-template', defaults: new Codicon('notebook-template', { fontCharacter: '\\ebbf' }) },
    // { id: 'debug-rerun', defaults: new Codicon('debug-rerun', { fontCharacter: '\\ebc0' }) },
    // { id: 'workspace-trusted', defaults: new Codicon('workspace-trusted', { fontCharacter: '\\ebc1' }) },
    // { id: 'workspace-untrusted', defaults: new Codicon('workspace-untrusted', { fontCharacter: '\\ebc2' }) },
    // { id: 'workspace-unspecified', defaults: new Codicon('workspace-unspecified', { fontCharacter: '\\ebc3' }) },
    // { id: 'terminal-cmd', defaults: new Codicon('terminal-cmd', { fontCharacter: '\\ebc4' }) },
    // { id: 'terminal-debian', defaults: new Codicon('terminal-debian', { fontCharacter: '\\ebc5' }) },
    // { id: 'terminal-linux', defaults: new Codicon('terminal-linux', { fontCharacter: '\\ebc6' }) },
    // { id: 'terminal-powershell', defaults: new Codicon('terminal-powershell', { fontCharacter: '\\ebc7' }) },
    // { id: 'terminal-tmux', defaults: new Codicon('terminal-tmux', { fontCharacter: '\\ebc8' }) },
    // { id: 'terminal-ubuntu', defaults: new Codicon('terminal-ubuntu', { fontCharacter: '\\ebc9' }) },
    // { id: 'terminal-bash', defaults: new Codicon('terminal-bash', { fontCharacter: '\\ebca' }) },
    // { id: 'arrow-swap', defaults: new Codicon('arrow-swap', { fontCharacter: '\\ebcb' }) },
    // { id: 'copy', defaults: new Codicon('copy', { fontCharacter: '\\ebcc' }) },
    // { id: 'person-add', defaults: new Codicon('person-add', { fontCharacter: '\\ebcd' }) },
    // { id: 'filter-filled', defaults: new Codicon('filter-filled', { fontCharacter: '\\ebce' }) },
    // { id: 'wand', defaults: new Codicon('wand', { fontCharacter: '\\ebcf' }) },
    // { id: 'debug-line-by-line', defaults: new Codicon('debug-line-by-line', { fontCharacter: '\\ebd0' }) },
    // { id: 'inspect', defaults: new Codicon('inspect', { fontCharacter: '\\ebd1' }) }
// ];
