#
# Build image:
#    $ docker build -t theia-dev -f Dockerfile.dev .
#
# How to use this image
#
# theia-dev image helps make and run theia without installing anything on the host
# 1.  Build theia in docker:
#     $ docker run -e GITHUB_TOKEN="<token>" -v /path/to/theia-ide-sources-folder/:/home/theia theia-dev sh -c 'cd /home/theia; yarn'
#
#     Note that sometimes you can reach Github API rate limit, so to solve this issue please use env var GITHUB_TOKEN as per example
#
# 2.  Run theia sources in docker:
#     $ docker run -d -p 3000:3000 -v /path/to/theia-ide-sources-folder/:/home/theia theia-dev sh -c 'cd /home/theia/examples/browser; yarn run start --hostname 0.0.0.0'
#

FROM node:8
RUN useradd --create-home theia
WORKDIR /home/theia
RUN apt-get update && apt-get install -y git
USER theia
