blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url:  https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community&component=Vulnerability%20Reports&keywords=security&groups=Security_Advisories
    about: Please report security-related issues directly to the Eclipse Foundation. See our project's [SECURITY.md](https://github.com/eclipse-theia/theia/SECURITY.md) for more details
