/*
 * Copyright (C) 2017 Ericsson and others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 */

import { interfaces } from "inversify";
import {
    createPreferenceProxy,
    PreferenceProxy,
    PreferenceService,
    PreferenceContribution,
    PreferenceSchema
} from '@theia/preferences/lib/common';

export const CLANGD_COMMAND_DEFAULT = 'clangd';

export const CppConfigSchema: PreferenceSchema = {
    "type": "object",
    "properties": {
        "cpp.clangdCompilationDatabaseDirectory": {
            "type": "string",
            "description": "Path to the Compilation Database directory (containing compile_commands.json). " +
                "This file contains compiler commands for each source files which are important for clangd to properly analyze files. " +
                "It can be generated by several tools such as CMake."
        },
        "cpp.clangdCommand": {
            "type": "string",
            "description": "Command to launch the clangd executable."
        },
        "cpp.clangdCommandArgs": {
            "type": "array",
            "description": "Arguments to the clangd command."
        }
    }
};

export interface CppConfiguration {
    'cpp.clangdCompilationDatabaseDirectory': string,
    'cpp.clangdCommand': string,
    'cpp.clangdCommandArgs': string[]
}

export const defaultCppConfiguration: CppConfiguration = {
    'cpp.clangdCompilationDatabaseDirectory': '',
    'cpp.clangdCommand': CLANGD_COMMAND_DEFAULT,
    'cpp.clangdCommandArgs': []
};

export const CppPreferences = Symbol('CppPreferences');
export type CppPreferences = PreferenceProxy<CppConfiguration>;

export function createCppPreferences(preferences: PreferenceService): CppPreferences {
    return createPreferenceProxy(preferences, defaultCppConfiguration, CppConfigSchema);
}

export function bindCppPreferences(bind: interfaces.Bind): void {
    bind(CppPreferences).toDynamicValue(ctx => {
        const preferences = ctx.container.get(PreferenceService);
        return createCppPreferences(preferences);
    });

    bind(PreferenceContribution).toConstantValue({ schema: CppConfigSchema });
}
