name: Build-Native-Dependencies

on: workflow_dispatch

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: yarn prebuild:native-dependencies
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3 
      with: 
        name: native-dependencies
        path: ./prebuild-native-dependencies/*.zip
