name: Playwright Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "doc/**"
      - "logo/**"
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "doc/**"
      - "logo/**"
  schedule:
    - cron: "0 4 * * *" # Runs every day at 4am: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

jobs:
  build-and-test-playwright:
    name: Playwright Tests (ubuntu-22.04,  Node.js 24.x)

    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node.js "24.x"
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Use Python 3.13
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"

      - name: Install IPython Kernel
        shell: bash
        run: |
          python3 -m pip install ipykernel==6.15.2
          python3 -m ipykernel install --user

      - name: Build Browser
        shell: bash
        run: |
          npm ci
          npm run build:browser
          npm run download:plugins
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9

      - name: Build Playwright
        shell: bash
        run: |
          cd examples/playwright && npm run build

      - name: Test (playwright)
        shell: bash
        run: cd examples/playwright && npm run ui-tests-ci

      - name: Archive test results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: ${{ !cancelled() }}
        with:
          name: playwright-test-results
          path: |
            examples/playwright/test-results/
            examples/playwright/playwright-report/
          retention-days: 7
