name: Production Build Smoke Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - 'doc/**'
      - 'logo/**'
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - 'doc/**'
      - 'logo/**'

jobs:
  build-and-test-playwright:
    name: Smoke Test for Browser Example Production Build on ubuntu-22.04 with Node.js 24.x

    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node.js "24.x"
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Use Python 3.13
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"

      - name: Build Browser Example Application for Production
        shell: bash
        run: |
          npm ci
          cd examples/browser && npm run build:production
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9

      - name: Build Playwright
        shell: bash
        run: |
          cd examples/playwright && npm run build

      - name: Run Smoke Test (examples/playwright/src/tests/theia-app)
        shell: bash
        run: npm run test:playwright -- theia-app
