name: Publish Release

permissions:
  id-token: write

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'minor'
          - 'patch'

jobs:
  publish:
    name: Perform Publishing
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Use Node.js 20.x
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Use Python 3.11
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: "3.11"

      - name: Install
        shell: bash
        run: |
          yarn global add node-gyp
          yarn --skip-integrity-check --network-timeout 100000
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9

      - name: Publish NPM
        shell: bash
        run: |
          yarn publish:latest -- ${{ inputs.release_type }}
          yarn publish:check
        env:
          NPM_CONFIG_PROVENANCE: "true" # enable provenance check
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Get Actor User Data
        uses: octokit/request-action@21d174fc38ff59af9cf4d7e07347d29df6dbaa99 # v2.3.0
        id: actor_user_data
        with:
          route: GET /users/{user}
          user: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with:
          commiter: ${{ github.actor }} <${{ fromJson(steps.actor_user_data.outputs.data).email }}>
          author: ${{ github.actor }} <${{ fromJson(steps.actor_user_data.outputs.data).email }}>
          branch: bot/package-update
          title: Package update for version ${{ env.NEXT_VERSION_NUMBER }}
          commit-message: Package update for version ${{ env.NEXT_VERSION_NUMBER }}
          body: Automated package update for Theia version ${{ env.NEXT_VERSION_NUMBER }}. Triggered by @${{ github.actor }}.
